FROM node:20
WORKDIR /usr/local/app
COPY package*.json .
ENV USE_MEMORY_DB=true \
DATABASE_URI=mongodb://localhost:27017/notes \
PORT=3000

EXPOSE 3000
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build
CMD ["node", "dist/main.js"]