# Use the official Node.js image as a base
FROM node:20 AS base
WORKDIR /usr/local/app
# Set environment variables
ENV USE_MEMORY_DB=true \
    DATABASE_URI=mongodb://localhost:27017/notes \
    PORT=3000

# Expose port (the port your backend app listens on)
EXPOSE $PORT

# Install dependencies
COPY ./package*.json ./
RUN npm install --legacy-peer-deps

# Copy backend code into the container
COPY . .

CMD [ "npm", "run", "start" ]

