# docker compose  -p todo-1 -f .\compose_1.yaml up -d
version: "3"

services:
  web:
    depends_on:
      - backend
    image: silvelo/todo-client
    container_name: ${COMPOSE_PROJECT_NAME}_client
    hostname: todo-client
    networks:
      - client-network
    ports:
      - "8080:80"
    volumes:
      #- ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-conf:/etc/nginx
  backend:
    image: silvelo/todo-backend
    networks:
      - client-network
    hostname: todo-backend
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    #environment:
    #- DATABASE_URI=mongodb://mongo:27017/todo
    #- USE_MEMORY_DB=true
    #- PORT=3000
    ports:
      - "3000:3000"

networks:
  client-network:

volumes:
  nginx-conf:
    driver: local
    driver_opts:
      type: none
      device: ./nginx
      o: bind
